import Foundation

/// Pasteboard type markers defined by the de-facto nspasteboard.org convention.
/// Well-behaved apps (password managers, etc.) set these so clipboard managers
/// can decide whether to record an item — without reading its contents.
public enum PasteboardMarker: String, Sendable, Equatable, CaseIterable {
    /// Confidential content (passwords). Do not record in plaintext.
    case concealed = "org.nspasteboard.ConcealedType"
    /// Momentary content that should never be recorded.
    case transient = "org.nspasteboard.TransientType"
    /// App-generated content the user did not deliberately copy.
    case autoGenerated = "org.nspasteboard.AutoGeneratedType"
}

/// Why a piece of content was heuristically judged sensitive.
public enum SecretReason: String, Sendable, Equatable, CaseIterable {
    case privateKey
    case jwt
    case creditCard
    case apiKey
    case highEntropy
}

/// The sensitivity verdict for a captured item.
public enum SensitivityClassification: Sendable, Equatable {
    /// Ordinary content; store and display normally.
    case normal
    /// Marked confidential by the source app (nspasteboard `ConcealedType`).
    case concealedByMarker
    /// Marked transient; must not be recorded at all.
    case transient
    /// Detected as a secret by content heuristics.
    case detectedSecret(reason: SecretReason)

    /// Whether the item should be stored encrypted and masked rather than plain.
    public var isSensitive: Bool {
        switch self {
        case .normal, .transient: return false
        case .concealedByMarker, .detectedSecret: return true
        }
    }

    /// Whether the item must be dropped instead of recorded.
    public var shouldDiscard: Bool {
        if case .transient = self { return true }
        return false
    }
}
